package com.sellgirl.sellgirlPayDomain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table test
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Test {
    private Long id;

    private String v;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getV() {
        return v;
    }

    public void setV(String v) {
        this.v = v == null ? null : v.trim();
    }
}